// Copyright (C) 2016, Jean-Pierre de la Croix
// see LICENSE included with this software

#ifndef _SABRE_CONSTANTS_HPP_
#define _SABRE_CONSTANTS_HPP_

#define SABRE_STEERING_TARGET_LEFT      3600    //  900us
#define SABRE_STEERING_TARGET_NEUTRAL   5600    // 1400us
#define SABRE_STEERING_TARGET_RIGHT     7600    // 1900us

#define SABRE_THROTTLE_TARGET_FORWARD         8000    // 2000us
#define SABRE_THROTTLE_TARGET_FORWARD_SLOW    6448    // 1612us
#define SABRE_THROTTLE_TARGET_NEUTRAL         6048    // 1512us
#define SABRE_THROTTLE_TARGET_REVERSE_SLOW    5648    // 1412us
#define SABRE_THROTTLE_TARGET_REVERSE         4096    // 1024us

#define SABRE_STEERING_CHANNEL    1
#define SABRE_THROTTLE_CHANNEL    3

#endif
